/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.ranger.binding.metastore.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TOperation implements org.apache.thrift.TEnum {
  CREATE_DATABASE(0),
  DROP_DATABASE(1),
  CREATE_TABLE(2),
  DROP_TABLE(3),
  ALTER_TABLE(4),
  REMAME_TABLE(5),
  ADD_PARTITION(6),
  DROP_PARTITION(7),
  ALTER_PARTITION(8),
  RENAME_PARTITION(9),
  INIT_ID(10);

  private final int value;

  private TOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TOperation findByValue(int value) { 
    switch (value) {
      case 0:
        return CREATE_DATABASE;
      case 1:
        return DROP_DATABASE;
      case 2:
        return CREATE_TABLE;
      case 3:
        return DROP_TABLE;
      case 4:
        return ALTER_TABLE;
      case 5:
        return REMAME_TABLE;
      case 6:
        return ADD_PARTITION;
      case 7:
        return DROP_PARTITION;
      case 8:
        return ALTER_PARTITION;
      case 9:
        return RENAME_PARTITION;
      case 10:
        return INIT_ID;
      default:
        return null;
    }
  }
}
